## 한개일때
* H(x) = Wx + b

## 여러 개
* H(x1, x2) = w1x1 + w2x2 + b

### 번거로우니까 Matrix 사용

* 곱셈만 사용할거임
### H(x) = XW
* 매트릭스는 대문자 사용
* 여러 인스턴스 한꺼번에 계산 가능

In [5]:
import tensorflow as tf

# 그냥버전
x1_data = [73, 93, 89, 96, 73]
x2_data = [80, 88, 91, 98, 66]
x3_data = [75, 93, 90, 100, 70]
y_data = [152., 185., 180., 196., 142]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1*w1 + x2*w2 + x3*w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - y))

# learning_rate = 1e-5
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1:x1_data, x2:x2_data, x3:x3_data, y:y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  43957.695 
Prediction:
 [-30.74328  -41.580753 -38.4      -42.4462   -32.640755]
100 Cost:  8.028572 
Prediction:
 [155.16232 182.06952 181.85962 197.42154 137.99052]
200 Cost:  7.6212645 
Prediction:
 [155.0564  182.14232 181.82736 197.3966  138.08737]
300 Cost:  7.235429 
Prediction:
 [154.95332 182.21315 181.79597 197.37234 138.18167]
400 Cost:  6.87 
Prediction:
 [154.85303 182.28206 181.76544 197.3487  138.27344]
500 Cost:  6.5237517 
Prediction:
 [154.75542 182.34914 181.73573 197.32564 138.3628 ]
600 Cost:  6.1957994 
Prediction:
 [154.66045 182.41441 181.70683 197.30316 138.44975]
700 Cost:  5.885072 
Prediction:
 [154.56802 182.47794 181.67873 197.28128 138.53445]
800 Cost:  5.5907326 
Prediction:
 [154.47807 182.53973 181.65135 197.2599  138.61687]
900 Cost:  5.311878 
Prediction:
 [154.39056 182.59988 181.62473 197.23909 138.69713]
1000 Cost:  5.047717 
Prediction:
 [154.3054  182.65845 181.59883 197.21884 138.77525]
1100 Cost:  4.797496 
Prediction:
 [154.22253 182