In [2]:
import tensorflow as tf

# Matrix
x_data = [[73, 80, 75], [93, 88, 93], [89, 91, 90], [96, 98, 100], [73, 66, 70]]
y_data = [[152], [185], [180], [196], [142]]

x = tf.placeholder(tf.float32, shape = [None ,3])
y = tf.placeholder(tf.float32, shape = [None, 1])

w = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(x, w) + b

cost = tf.reduce_mean(tf.square(hypothesis - y))

# learning_rate = 1e-5
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x:x_data, y:y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  34056.023 
Prediction:
 [[-12.615292]
 [-12.140572]
 [-13.542793]
 [-13.067066]
 [-10.150173]]
100 Cost:  1.8961643 
Prediction:
 [[151.1082 ]
 [184.67532]
 [180.36685]
 [198.09154]
 [139.98233]]
200 Cost:  1.8762257 
Prediction:
 [[151.09181]
 [184.68712]
 [180.36256]
 [198.0827 ]
 [140.00267]]
300 Cost:  1.8569965 
Prediction:
 [[151.07591]
 [184.69858]
 [180.35841]
 [198.07397]
 [140.02254]]
400 Cost:  1.8384422 
Prediction:
 [[151.06055]
 [184.70972]
 [180.35446]
 [198.06541]
 [140.04199]]
500 Cost:  1.8205563 
Prediction:
 [[151.04562]
 [184.72052]
 [180.35062]
 [198.05695]
 [140.06096]]
600 Cost:  1.8032627 
Prediction:
 [[151.03116]
 [184.731  ]
 [180.3469 ]
 [198.04858]
 [140.07951]]
700 Cost:  1.7865387 
Prediction:
 [[151.01717]
 [184.74117]
 [180.34334]
 [198.04033]
 [140.09766]]
800 Cost:  1.77038 
Prediction:
 [[151.0036 ]
 [184.75107]
 [180.3399 ]
 [198.0322 ]
 [140.11539]]
900 Cost:  1.7547519 
Prediction:
 [[150.99046]
 [184.76064]
 [180.33661]
 [198.02417]
 [1