* Activation Functions

* Backpropagation
 * Paul Werbos 1974, 1982
 * Hinton 1986
* Convolutional Neural Networks

In [1]:
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank 차원, 괄호 수
print(t.shape) # shape 원소 수
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [3]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


In [4]:
# 괄호 안쪽부터 센다
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4])

In [5]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2])

In [6]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

In [7]:
# Axis = 축
# 제일 안쪽에 있는게 제일 큰값
# 제일 밖에 있는게 0
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

In [12]:
# Matmul
matrix1 = tf.constant([[1., 2.],[3.,4.]])
matrix2 = tf.constant([[1.],[2.]])
print("Matrix 1 shape", matrix1.shape)
print("Matrix 2 shape", matrix2.shape)
tf.matmul(matrix1, matrix2).eval()

Matrix 1 shape (2, 2)
Matrix 2 shape (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [13]:
# Multiply
(matrix1*matrix2).eval()

array([[1., 2.],
       [6., 8.]], dtype=float32)

### Broadcasting

In [16]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)
(matrix1+matrix2).eval()

array([[4., 5.]], dtype=float32)

In [17]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3., 4.]])
(matrix1+matrix2).eval()

array([[4., 6.]], dtype=float32)

In [18]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.], [4.]])
(matrix1+matrix2).eval()

array([[4., 5.],
       [5., 6.]], dtype=float32)

### Reduce mean

In [19]:
tf.reduce_mean([1, 2], axis=0).eval()

1

In [20]:
x = [[1., 2.],
     [3., 4.]]


tf.reduce_mean(x).eval()

2.5

In [21]:
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [22]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [23]:
tf.reduce_mean(x, axis=-1).eval()

array([1.5, 3.5], dtype=float32)

### Reduce sum

In [24]:
tf.reduce_sum(x).eval()

10.0

In [25]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [26]:
tf.reduce_sum(x, axis=-1).eval()

array([3., 7.], dtype=float32)

In [27]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

### Argmax

In [32]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [33]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [34]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)

### Reshape**

In [35]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [36]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

* squeeze

In [38]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2])

* expand

In [39]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]])

### One hot

In [40]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()
# auto rank expand

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [41]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

### Casting

In [42]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [43]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

### Stack

In [44]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [46]:
tf.stack([x, y, z], axis=0).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

### Ones like and Zeros like

In [60]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [61]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

### Zip

In [51]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [52]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


### Transpose

In [53]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [54]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [55]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [56]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [57]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
